let shopItemsData = [{
    id: "a",
    name: "Formal Shirt",
    price: 2000,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/shirt.jpg",
}, 
{
    id: "b",
    name: "Jeans",
    price: 3000,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/jeans.jpg",
}, 
{
    id: "c",
    name: "Kurta Men",
    price: 1100,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/kurta.jpg",
}, 
{
    id: "d",
    name: "Dress Floral",
    price: 2050,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/dress.jpg",
},
{
    id: "e",
    name: "Suit Men",
    price: 8599,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/suit.jpg",
},
{
    id: "f",
    name: "Elegant Saree",
    price: 4900,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/saree.jpg",
},
{
    id: "g",
    name: "Tie Men",
    price: 1099,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/tie.jpg",
},
{
    id: "h",
    name: "Plain Black",
    price: 4300,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/blackdress.jpg",
},
{
    id: "i",
    name: "Casual Women",
    price: 3999,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/casualfit.jpg",
},
{
    id: "j",
    name: "Tshirt Men",
    price: 1300,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/tshirt.jpg",
},
{
    id: "k",
    name: "Denim Jacket",
    price: 3300,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/denim.jpg",
},
{
    id: "l",
    name: "Casual Men",
    price: 3800,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/casualmen.jpg",
},
];